version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: "diplom"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./back/db:/var/lib/mysql
    networks:
      diplom-network:
        aliases:
          - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    networks:
      - diplom-network
    environment:
      PMA_HOST: "database"
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
  migrations:
networks:
  diplom-network:
