version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: "diplom"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
  back:
    container_name: back
    links:
      - db
    build:
      context: ./back
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
    - 8081:8081
    volumes:
    - ./back:/back
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  proxy_server:
    image: nginx:latest
    container_name: proxy_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - back
      - front
